service: test-message-user # OJO: Solo en caso de que ya exista una App Engine

# SOURCE: https://cloud.google.com/appengine/docs/the-appengine-environments

#################################################################################
# CASE 1: Standard environment AppEngine
#################################################################################
#runtime: python37

#entrypoint: gunicorn -b :$PORT main:app

#################################################################################
# CASE 2: Flexible Environment AppEngine
#################################################################################
runtime: python
env: flex
runtime_config:
    python_version: 3

manual_scaling:
  instances: 2
resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 10  # Disk size must be between 10GB and 10240GB

entrypoint: gunicorn -b :$PORT main:app
#################################################################################